### ISSUE TITLE
failing to catch effective since_id

### ISSUE THREAD

**Issue by a-shiomaneki** [rbtnn/mstdn-picker#1]
status取得ループの終了条件でstatus のidとsince_id の一致するか否かを見ていますが，おそらく非収載か未公開のためかidが一致するstatus が取得できない場合があります．この場合，終了条件を満たせずcount数一杯までsince_id以前のstatusまで取得しているようです．

**Comment by rbtnn** [comment]
@a-shiomaneki 以下のPRをマージしてみたんですが、パラメータが`?instance=mstdn.guru&since_id=1&max_id=2`の時、うまくいかなくなりました。

https://github.com/rbtnn/mstdn-picker/pull/2

PRをマージしましたが、一回revertします。

**Comment by a-shiomaneki** [comment]
了解です．私も確認してみます．
原因がわかりました．
以下のresponseからstatusを取り込むループで，responseの最後のstatusで必用なstatusの取り込みを終了させなければならないような条件，例えばmstdn.guru の max_id=2, since_id=1の時，for内のif文の条件に合致することなくforループをぬけてしまいます．このときに`flag=true`のままなのが誤動作の原因でした．
```             var flag = true;
            var last_max_id = '';
            for (var i in response){
                count--;
                if ((count < 0) || (response[i].id < since_id)) {
                    flag = false;
                    break;
                }
                last_max_id = response[i].id;
                // prependChild
                STATUS_LIST.insertBefore(new_status(response[i]), STATUS_LIST.firstChild);
            }
            if (flag){
                get_status_sub(instance, last_max_id, since_id, count, callback4localst);
            }
            else{
                callback4localst();
            }
```
そこでこの問題の条件の時に`flag=false`にするif文を書き加えました．後ほどのこの修正のPRをお送りします．

**Comment by rbtnn** [comment]
@a-shiomaneki 
#5 をざっくり試した感じ問題なさそうですね。
こちらも数日か触ってみて、問題が起きなそうならこのissueもcloseします。
Issue及びPRありがとうございました。

**Comment by rbtnn** [comment]
@a-shiomaneki 問題なさそうなのでクローズします。ありがとうございました。
