### ISSUE TITLE
capability of filter parameter at http get method

### ISSUE THREAD

**Issue by a-shiomaneki** [rbtnn/mstdn-picker#3]
filterの値をhttpのgetメソッドで指定できる機能が欲しいです．
特定の話題の記録に用いる場合，そのままだと関係の無いトゥートまで含まれてしまうためSNが悪くなり記録としての価値を落としてしまいます．

**Comment by rbtnn** [comment]
数日か触ってみて、問題が起きなそうならこのissueもcloseします。

**Comment by a-shiomaneki** [comment]
了解です．よろしくお願いいたします．

**Comment by rbtnn** [comment]
@a-shiomaneki 問題なさそうなのでクローズします。ありがとうございました。
